version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2022
configuration: Release
environment:
  UseTemporarySignCert: true
install:
- ps: choco install innosetup -y --no-progress
before_build:
- ps: dotnet restore src\WinDynamicDesktop.sln /p:VersionSuffix={build}
build:
  verbosity: minimal
after_build:
- ps: powershell scripts\package.ps1
artifacts:
- path: dist\WinDynamicDesktop_*_Portable.exe
  name: Portable EXE
- path: dist\WinDynamicDesktop_*_Setup.exe
  name: Installer package
- path: uwp\AppPackages\**\WinDynamicDesktop*.appxbundle
  name: UWP app package
