name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64, arm64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: microsoft/setup-msbuild@v1

    - run: dotnet restore src\WinDynamicDesktop.sln

    - run: dotnet publish src\WinDynamicDesktop.csproj -a ${{ matrix.platform }} -c Release --no-restore --self-contained --version-suffix $(git rev-parse --short HEAD) -p:EnableCompressionInSingleFile=true -p:PublishSingleFile=true

    # TODO Remove usage of temporary cert
    - run: msbuild uwp\WinDynamicDesktop.Package.wapproj /p:AppxBundle=Never /p:Configuration=Release /p:Platform=${{ matrix.platform }} /p:UapAppxPackageBuildMode=SideloadOnly /p:UseTemporarySignCert=true

    - uses: actions/upload-artifact@v3
      with:
        name: exe-${{ matrix.platform }}
        path: src\bin\Release\**\publish\*.exe

    - uses: actions/upload-artifact@v3
      with:
        name: msix-${{ matrix.platform }}
        path: uwp\AppPackages\**\*.msix
