name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        description: Tag of release you want to publish
        type: string
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: t1m0thyj.WinDynamicDesktop
          installers-regex: 'Setup\.exe$'
          release-tag: ${{ inputs.release_tag || github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}
